version: 2
jobs:
    build:
        working_directory: ~/app
        docker:
            - image: node:10
        steps:
            - checkout
            - run:
                name: Install Dependencies
                command: yarn install
            - run:
                name: Flow and lint
                command: yarn run pre-release
            - run:
                name: Test
                command: yarn run test
    build_stage_docker:
        working_directory: ~/app
        docker:
            - image: alpine
        environment:
            REGISTRY: "registry.gitlab.com/goodjoblife/i/goodjob-admin-page"
        steps:
            - checkout
            - run:
                name: Install Docker client & Docker Compose
                command: |
                    apk add --update docker py-pip
                    pip install docker-compose
            - setup_remote_docker
            - run:
                name: Login docker registry
                command: docker login registry.gitlab.com -u ${DOCKER_REGISTRY_USER} -p ${DOCKER_REGISTRY_PASS}
            - run:
                name: Build Docker and Push
                command: |
                    if [ "${CIRCLE_PROJECT_USERNAME}" == "goodjoblife" ]; then
                        # build
                        docker-compose -f .circleci/docker-compose-stage.yml build
                        docker tag "goodjob-admin-page:stage" "${REGISTRY}:stage"
                        # push
                        docker push "${REGISTRY}:stage"
                    fi
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - build_stage_docker:
                filters:
                    branches:
                        only: master
