version: 2
jobs:
    build:
        working_directory: ~/app
        docker:
            - image: node:10
        steps:
            - checkout
            - run:
                name: Install Dependencies
                command: yarn install
            - run:
                name: Flow and lint
                command: yarn run pre-release
            - run:
                name: Test
                command: yarn run test
    build_stage_docker:
        working_directory: ~/app
        docker:
            - image: alpine
        environment:
            REGISTRY: "reg.goodjob.life/goodjob/admin-page"
        steps:
            - checkout
            - run:
                name: Install Docker client & Docker Compose
                command: |
                    apk add --update docker py-pip
                    pip install docker-compose==1.23.2
            - setup_remote_docker
            - run:
                name: Login docker registry
                command: docker login reg.goodjob.life -u ${DOCKER_REGISTRY_USER} -p ${DOCKER_REGISTRY_PASS}
            - run:
                name: Build Docker and Push
                command: |
                    if [ "${CIRCLE_PROJECT_USERNAME}" == "goodjoblife" ]; then
                        # build
                        docker-compose -f .circleci/docker-compose-stage.yml build
                        docker tag "goodjob-admin-page:stage" "${REGISTRY}:stage"
                        # push
                        docker push "${REGISTRY}:stage"
                    fi
    build_production_docker:
        working_directory: ~/app
        docker:
            - image: alpine
        environment:
            REGISTRY: "reg.goodjob.life/goodjob/admin-page"
        steps:
            - checkout
            - run:
                name: Install Docker client & Docker Compose
                command: |
                    apk add --update docker py-pip
                    pip install docker-compose==1.23.2
            - setup_remote_docker
            - run:
                name: Login docker registry
                command: docker login reg.goodjob.life -u ${DOCKER_REGISTRY_USER} -p ${DOCKER_REGISTRY_PASS}
            - run:
                name: Build Docker and Push
                command: |
                    if [ "${CIRCLE_PROJECT_USERNAME}" == "goodjoblife" ]; then
                        # build
                        docker-compose -f .circleci/docker-compose-production.yml build
                        docker tag "goodjob-admin-page:production" "${REGISTRY}:production-${CIRCLE_SHA1}"
                        # push
                        docker push "${REGISTRY}:production-${CIRCLE_SHA1}"
                    fi
    deploy_stage:
        working_directory: ~/app
        docker:
            - image: alpine
        steps:
            - run: apk add --update curl
            - run:
                name: Trigger Deploy
                command: |
                    if [ "${CIRCLE_PROJECT_USERNAME}" == "goodjoblife" ]; then
                        curl --user ${CIRCLE_API_TOKEN_FOR_DEPLOY}: \
                            --data build_parameters[CIRCLE_JOB]=build \
                            https://circleci.com/api/v1.1/project/github/mark86092/goodjob-deploy-ci/tree/site/admin-page-stage
                    fi
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - build_stage_docker:
                filters:
                    branches:
                        only: master
            - build_production_docker:
                filters:
                    branches:
                        only: master
            - deploy_stage:
                requires:
                    - build
                    - build_stage_docker
                filters:
                    branches:
                        only: master
