name: Github Actions CI

on:
  push:
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install
      - name: Flow and lint
        run: yarn run pre-release
      - name: Test
        run: yarn run test
  docker-production:
    name: Deploy docker image
    if: github.repository == 'goodjoblife/goodjob-admin-page' && github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - test
    env:
      REGISTRY: docker.pkg.github.com
      REPO: goodjoblife/goodjob-admin-page/admin-page-web-server
      IMAGE: goodjob-admin-page:production
    steps:
      - uses: actions/checkout@v2
      - run: docker login ${REGISTRY} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - run: docker-compose -f .github/docker-compose-production.yml build
      - run: docker tag ${IMAGE} ${REGISTRY}/${REPO}:production-${GITHUB_SHA}
      - run: docker push ${REGISTRY}/${REPO}:production-${GITHUB_SHA}
  docker-stage:
    name: Deploy docker image
    if: github.repository == 'goodjoblife/goodjob-admin-page' && github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - test
    env:
      REGISTRY: docker.pkg.github.com
      REPO: goodjoblife/goodjob-admin-page/admin-page-web-server-dev
      IMAGE: goodjob-admin-page:stage
    steps:
      - uses: actions/checkout@v2
      - run: docker login ${REGISTRY} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - run: docker-compose -f .github/docker-compose-stage.yml build
      - run: docker tag ${IMAGE} ${REGISTRY}/${REPO}:stage
      - run: docker push ${REGISTRY}/${REPO}:stage
  deploy-stage:
    if: github.repository == 'goodjoblife/goodjob-admin-page' && github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - docker-stage
    steps:
      - name: Deploy stage
        run: |
          curl --user "${{ secrets.DEPLOY_CI_TOKEN }}" \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"event_type": "goodjobadminpage-stage-published"}' \
            https://api.github.com/repos/mark86092/goodjob-deploy-ci/dispatches
